Revert "Remove redundant "std::move"s in return statements"
The build failed with

  error: call to deleted constructor of 'llvm::Error'

errors.

This reverts commit 6eb465d7d98755a16b77fba58ed032264b16bcd9.