Revert "ADT: SmallVector size/capacity use word-size integers when elements are small"
This reverts commit 5b6a7f51e6a9221b11bf28edf616869a4f923f98.

clang-cmake-armv7-quick/llvm/llvm/lib/Support/SmallVector.cpp:81:22:
error: duplicate explicit instantiation of 'SmallVectorBase<unsigned int>'