Revert "[llvm] add zstd to llvm::compression namespace"
This reverts commit e65ae00336a3e330f686e069bb51ebc719decdaa.

Breaks macOS builds with this:
llvm/lib/Support/Compression.cpp:24:10: fatal error: 'zstd.h' file not found