Temporarily revert "Add a facility to get system cache directory and use it in clangd"
This reverts commit d6f40780512484e6dd893bce6dd61af84d9ce9cc.

As it broke building the unittests:

.../sources/llvm-project/llvm/unittests/Support/Path.cpp:334:5: error: use of undeclared identifier 'set'
    set(Value);
    ^
1 error generated.