Revert "[LoopVectorizer] Inloop vector reductions"
This reverts commit 15819dded45a6299cdefc44b6a1c73202da1cf00. It breaks the build:

```
~/src/llvm-project/llvm/lib/Analysis/IVDescriptors.cpp:868:10: error: no viable conversion from returned value of type 'SmallVector<[...], 8>' to function return type 'SmallVector<[...], 4>'
  return ReductionOperations;
```