Revert "[ADT] Support const-qualified unique_functions"
This reverts commit e2abc937c478e9bb5d0e82b508dd60f55717f8ec.

Breaks the build:

llvm/include/llvm/ADT/FunctionExtras.h:223:7: error: explicit template argument list not allowed
  223 |       Callbacks<CallableT, CalledAs, EnableIfTrivial<CallableT>>;