Revert "lit: revert 000913ea0e0c53a357f74ea5b5346caf01afa8c9"
This reverts commit 5b5af3b0d39ffd4c51880df3169f57dc5c4b8994.

Causing messages like:

  File "...\Python\Python39\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 74