Revert "[InferAttrs] Add writeonly to all the math functions"
This reverts commit 6b59647dcbc4da349ddd4997ed83857ca06daf38 and
413066568b177bc890c69ac44324a22a2691049f.

That commit caused crashes with compilation e.g. like this
(not fixed by the follow-up commit):

$ cat sqrt.c
float a;
b() { sqrt(a); }
$ clang -target x86_64-linux-gnu -c -O2 sqrt.c
Attributes 'readnone and writeonly' are incompatible!
  %sqrtf = tail call float @sqrtf(float %0) #1
in function b
fatal error: error in backend: Broken function found, compilation aborted!